server:
  port: 8081


spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: mmmmmm
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
